### ISSUE TITLE
MarketplaceWebService_Client' not found in C:\wamp64\www\amazon-mws-master-rebuy-de\Samples\SubmitFeedSample.php on line 70

### ISSUE THREAD

**Issue by djp-narola** [rebuy-de/amazon-mws#4]
i was get this type of error.
can you pleace reply Where is I wrong? 

![1](https://user-images.githubusercontent.com/49981827/56845196-dfe50c00-68da-11e9-8004-0d401844d75e.png)

**Comment by Spea** [comment]
It looks like the autoloading used in the `config.inc.php` no longer works as expected. This library is actually quite outdated and we also no longer use it. If you want to use amazon mws services, you should use the following library which is more up2date and actually maintained https://github.com/WeengsApp/amazon-mws-client

Following this, I will archive this repository, sorry if it caused any troubles for you.
